### ISSUE TITLE
Book dinner in Stratford (table for X people)

### ISSUE THREAD

**Issue by just-simon-5** [Eco-Flow/ecoflow.github.io#8]

**Comment by just-simon-5** [comment]
I have curated a short list of restaurants:
https://docs.google.com/document/d/1BSdEzq2MarDR4K8jK_6_lOZMl1z8mwV4mu2sJD4Svhc/edit?usp=sharing

Chris and I will explore in person when we head to UCL east on the 17th. In the meantime I have sent the list to Yannick and Seirian to look at

**Comment by chriswyatt1** [comment]
Seirian has looked through the options, I think she thought the ones with specified vegan/veg options were best (Figo, she thought may work). We can see them in person next week

**Comment by chriswyatt1** [comment]
Booked Figo for 31 people. We have to pay 20£ per person in advance. And this money will come off our final bill. 

FOR 6pm, slightly earlier, but it means the drinks reception will be 1.30 hours,,, which is probably enough time to socialise. With more after in the restaurant and bars after (potentially)

**Comment by chriswyatt1** [comment]
I need to pay the deposit... which I will as soon as they send the confirmation email.

We can preorder, if we want food to come at the same time, but this could be major ball ache, so maybe easier to get people to order during a break, have a menu, and they choose what they want, and we send the restaurant the list
