### ISSUE TITLE
Organise brochure for the event

### ISSUE THREAD

**Issue by just-simon-5** [Eco-Flow/ecoflow.github.io#9]
This brochure should include:
directions to venues (seminar, dinner and hotels)
snippet of info on everyone attending
some key ecoflow links (github, website etc)

**Comment by chriswyatt1** [comment]
It should include the schedule for the day.
Where is the googe doc?
It should also be made into a (maybe single A4 folded page) booklet (we can discuss)

**Comment by just-simon-5** [comment]
Here's the link:
https://docs.google.com/document/d/1P3yRCLuNszvKNDJraJqQvG6OtOJT57AJ0HeOHCcRpDU/edit?usp=sharing

Depending on what information we want depends it's size but currently i am not sure it'll fit on 1 side of A4

**Comment by chriswyatt1** [comment]
If it is in a A4 sheet folded in half, we would have both sides of an A4 page, but maybe still too small. Just thought it could be a nice format, but could be another way (maybe it will just be electronic anyway, but could be nice printed for the event
)

**Comment by just-simon-5** [comment]
Brochure (A5 booklet):
Resources (back page - 4/4)
Schedule (front page - 1/4)
EcoFlow Team (front page - 1/4)
Ambassadors and attendees (middle pages - 2,3/4)

Travel and schedule will also go in official email along with each persons specific travel arrangements.

**Comment by just-simon-5** [comment]
Updated the brochure with a full design and layout:
currently 3 A4 pages folded in half to 6 A5 pages, using the details and layout Seirian asked for the attendees and ambassadors info, can have an extra page of A4 for notes
